#设置应用的根路径，如果不设置，访问路径为http://localhost:8080/，设置了之后，路径变为http://localhost:8080/demo/
#server:
#  servlet:
#    context-path: /demo

spring:
  profiles:
    # 当前项目启动激活的环境是dev(开发环境)
    active: dev
  config:
    #	通过spring.config.import导入其他配置文件
    import:
      - "classpath:springSecurity.yml"  # 导入同目录下的 springSecurity.yml
      - "classpath:jdbc.yml"  # 导入同目录下的 jdbc.yml
      - "classpath:redis.yml"  # 导入同目录下的 redis.yml
      - "classpath:mybatisPlus.yml"  # 导入同目录下的 mybatisPlus.yml

token:
  secret: spyVAlmCKL7NMJW2frntYVJUyQeyFzVtdlDHEYSIqWHp4H/wKpqVz2SNPjaE2WS7XhMcY37/vVc0IGYvebKN+w==  #accessToken加密密钥
  refresh-secret: MTCQ+jVSkyboQedcU5rWAnztQMOLPWAtLwZXmhVkfqnvQMQw69NDfNuP4Awx628Z4ET/idHdSnkTyMdJxD7Auw==   #refreshToken加密密钥
  expire-time: 1800      # accessToken有效时长30分钟
  refresh-expire-time: 7200  # refreshToken有效时长2小时
  refresh-time: 300       # accessToken剩余5分钟时触发刷新