# 基础配置（根据实际情况修改）
spring:
  data:
    redis:
      host: localhost
      port: 6379
      password:  # 无密码则留空
      database: 0  # 默认使用 0 号数据库
      lettuce:
        pool:
          max-active: 8  # 最大连接数
          max-idle: 4 # 最大空闲连接
          min-idle: 1 # 最小空闲连接
      timeout: 3000 # 3秒超时