# 统一后的云存储配置
cloud:
  storage:
    # 云存储厂商名称 (aliyun, qiniu, qcloud等)
    vendor: aliyun

    # 阿里云OSS相关配置
    aliyun:
      # 访问密钥ID (请在设备环境变量中添加对应环境变量，变量名为ALIBABA_ACCESS_KEY_ID（也可以修改变量名，同步修改即可）)
      # 设置环境变量命令（windows）：set ALIBABA_ACCESS_KEY_ID=xxx（临时设置，关闭命令行失效）    setx ALIBABA_ACCESS_KEY_ID "xxx"（用户变量（仅当前用户），永久设置）   setx /M ALIBABA_ACCESS_KEY_ID "xxx" （系统变量（所有用户），永久设置）
      # 验证是否生效：echo %ALIBABA_ACCESS_KEY_ID%
      # 设置环境变量命令（linux）:echo "export ALIBABA_ACCESS_KEY_ID=\"xxx\"" >> ~/.bashrc（写入配置文件 (Bash)）
      # 立即生效：source ~/.bashrc
      # 验证是否生效：echo $ALIBABA_ACCESS_KEY_ID
      # :表示环境变量不存在时注入空字符串
      # 注意：环境变量是针对进程的，所以设置环境变量后要重启IDEA，让新进程生效
      alibaba-access-key-id: ${ALIBABA_ACCESS_KEY_ID:}
      # 访问密钥 (请在设备环境变量中添加对应环境变量，变量名为ALIBABA_ACCESS_KEY_SECRET（也可以修改变量名，同步修改即可）)
      alibaba-access-key-secret: ${ALIBABA_ACCESS_KEY_SECRET:}
      # OSS存储桶名称 (请替换为您的实际值)
      bucket-name: xueyaxuetang
      # OSS服务端点 (请替换为您的实际端点)
      endpoint: http://oss-cn-hangzhou.aliyuncs.com
      # 图片上传路径
      image-upload-path: xyxt_img
      # OSS文件访问路径前缀
      image_oss_path_read: https://xueyaxuetang.oss-cn-region.aliyuncs.com